/**
 * Live integration tests — mirror of the Python SDK suite. Start a dev
 * server first with local unscored sessions enabled:
 * Start a compatible API host with local unscored sessions enabled.
 * The suite is skipped when that server is unreachable.
 */
import { describe, expect, it } from 'vitest';
import { ArenaClient, IllegalActionRejected } from '../src/index.js';

const BASE_URL =
  (globalThis as { process?: { env: Record<string, string | undefined> } }).process?.env[
    'ARENA_BASE_URL'
  ] ?? 'http://localhost:8899';

const up = await fetch(`${BASE_URL}/levels/lab/versions`).then(
  () => true,
  () => false,
);

// Current shortest authored-default route (generated by the engine solver).
const L1_OPTIMAL = [
  'Action 4', 'Action 1', 'Action 4', 'Action 1', 'Action 2',
  'Action 2', 'Action 2', 'Action 3', 'Action 2', 'Action 2',
  'Action 4', 'Action 4', 'Action 4', 'Action 1', 'Action 1',
  'Action 4', 'Action 1', 'Action 1', 'Action 1',
];

describe.skipIf(!up)('ArenaClient against a live server', () => {
  const client = new ArenaClient(BASE_URL);

  it('creates a session and plays the shortest current L1 run', async () => {
    const { sessionId, turn } = await client.createSession({
      gameMode: 'challenge',
      playMethod: 'human',
      levelId: 'od-l1',
    });
    expect(turn.grid).toContain('@');
    let t = turn;
    for (const id of L1_OPTIMAL) t = await client.submitAction(sessionId, { id });
    expect(t.status).toBe('won');
    // Published content can rebalance star thresholds independently of the
    // SDK fixture; verify the stable rating contract, not one R2 version.
    expect(t.stars).toBeGreaterThanOrEqual(1);
    expect(t.stars).toBeLessThanOrEqual(3);
    const summary = await client.submitSession(sessionId);
    expect(summary.transcriptLength).toBe(L1_OPTIMAL.length);
  });

  it('surfaces illegal actions as IllegalActionRejected', async () => {
    const { sessionId } = await client.createSession({
      gameMode: 'challenge',
      playMethod: 'human',
      levelId: 'od-l1',
    });
    await expect(client.submitAction(sessionId, { id: 'Action 1' })).rejects.toBeInstanceOf(
      IllegalActionRejected,
    );
  });

  it('drives an Object Usage session with index/xy params', async () => {
    const { sessionId } = await client.createSession({
      gameMode: 'challenge',
      playMethod: 'human',
      levelId: 'ou-l1',
    });
    for (const id of ['Action 4', 'Action 4', 'Action 4']) {
      await client.submitAction(sessionId, { id });
    }
    let t = await client.submitAction(sessionId, { id: 'Action 5', index: 0 });
    expect(t.hud.mode).toBe('targeting');
    expect(t.hud.targetableCells).toEqual([[1, 1], [2, 1], [3, 1], [3, 2]]);
    t = await client.submitAction(sessionId, { id: 'Action 5', x: 3, y: 2 });
    expect(t.hud.mode).toBe('normal');
  });
});
