"""Live-server integration tests: start a local Worker with unscored sessions:
`npm run dev -w @agilabs/worker -- --var DEV_ALLOW_ANY:true --var REQUIRE_AUTH:false`.
Point ARENA_BASE_URL at it; the suite is skipped when unreachable.
"""

import os
import urllib.error
import urllib.request

import pytest

from agilabs_arena import ArenaEnv, ArenaClient, IllegalActionRejected

BASE_URL = os.environ.get("ARENA_BASE_URL", "http://localhost:8899")

# Current shortest authored-default Object Delivery L1 route (generated by the
# engine solver). Human play keeps these canonical ids unpermuted.
L1_OPTIMAL = [
    "Action 4", "Action 1", "Action 4", "Action 1", "Action 2",
    "Action 2", "Action 2", "Action 3", "Action 2", "Action 2",
    "Action 4", "Action 4", "Action 4", "Action 1", "Action 1",
    "Action 4", "Action 1", "Action 1", "Action 1",
]


def _server_up() -> bool:
    try:
        urllib.request.urlopen(BASE_URL + "/levels/lab/versions", timeout=2)
        return True
    except (urllib.error.URLError, OSError):
        return False


pytestmark = pytest.mark.skipif(not _server_up(), reason=f"no server at {BASE_URL}")


def test_reset_returns_text_observation():
    env = ArenaEnv("od-l1", base_url=BASE_URL, play_method="human")
    obs, info = env.reset()
    assert "@" in obs["grid"]
    assert obs["legal_actions"]  # non-empty legal set
    assert all(a.startswith("Action ") for a in obs["legal_actions"])
    assert info["status"] == "playing"
    assert info["actions_used"] == 0
    assert obs["energy_left"] == info["max_actions"] - info["actions_used"]


def test_shortest_current_l1_run_wins_at_authored_rating():
    env = ArenaEnv("od-l1", base_url=BASE_URL, play_method="human")
    env.reset()
    total_reward = 0.0
    for action in L1_OPTIMAL:
        obs, reward, terminated, truncated, info = env.step(action)
        total_reward += reward
    assert terminated and not truncated
    assert info["status"] == "won"
    # Published R2 content may rebalance thresholds without changing the SDK.
    assert info["stars"] in (1, 2, 3)
    assert total_reward == float(info["stars"])
    summary = env.submit()
    assert summary["status"] == "won"
    assert summary["transcriptLength"] == len(L1_OPTIMAL)


def test_illegal_action_is_rejected_not_wasted():
    env = ArenaEnv("od-l1", base_url=BASE_URL, play_method="human")
    obs, _ = env.reset()
    assert "Action 1" not in obs["legal_actions"]  # wall above the start cell
    with pytest.raises(IllegalActionRejected):
        env.step("Action 1")
    # rejection must not consume energy
    turn = env.client.get_turn(env.session_id)
    assert turn.actions_used == 0


def test_scored_sessions_permute_wire_ids_sometimes():
    # Four legal ids are drawn from a shuffled nine-id alphabet. The chance of
    # retaining this exact set is 1/C(9,4) = 1/126 per session.
    canonical_first = {"Action 2", "Action 4", "Action 8", "Action 9"}
    saw_non_canonical = False
    for _ in range(8):
        _, turn = ArenaClient(BASE_URL).create_session(
            game_id="object-delivery", play_method="autonomous_scored"
        )
        if set(t for t in (a["id"] for a in turn.actions)) != canonical_first:
            saw_non_canonical = True
            break
    assert saw_non_canonical, "scored sessions never showed a permuted action set"
